version: "3.8"

services:
  astral:
    image: astral:dev
    container_name: astral
    ports:
      - 8000:8000
    #environment:
    #FORCE_HTTPS: "true"
    volumes:
      - ./app:/var/www/html/app:Z,U
      #- ./bootstrap:/var/www/html/bootstrap
      #- ./config:/var/www/html/config
      - ./database:/var/www/html/database:Z,U
      - ./resources:/var/www/html/resources:Z,U
      - ./routes:/var/www/html/routes:Z,U
      - ./storage/app:/var/www/html/storage/app:Z,U
    environment:
      DB_DATABASE: ${DB_DATABASE}
    command: >
      sh -c "chown www-data:www-data database -R && /usr/sbin/php-fpm7.4; /usr/sbin/nginx -g 'daemon off;'"
    networks:
      - astral-muracms-net

networks:
  astral-muracms-net:
    external: true
