version: "3.8"

# Backend
services:
  backend:
    image: astral:1.0.0-alpha.5
    container_name: astral
    ports:
      - 8000:8000
    #environment:
      #FORCE_HTTPS: "true"
    volumes:
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./storage:/var/www/html/storage

