// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(auth)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account")>;
      $$route?: undefined;
    },
    {
      path: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin")>;
    },
    {
      path: "/(auth)/register";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/register")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)/register")>;
    },
    {
      path: "/(auth)/sign-in";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/sign-in")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)/sign-in")>;
    },
    {
      path: "/(public)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(public)/index")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/(public)/index")>;
    },
    {
      path: "/account/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings")>;
      $$route?: undefined;
    },
    {
      path: "/(auth)/activate/:key";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/activate/[key]")>;
      $$route?: undefined;
    },
    {
      path: "/(public)/memberships/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(public)/memberships/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/(public)/memberships/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(public)/memberships/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/sales/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/sales/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/settings/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/settings/membership";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/membership")>;
      $$route?: undefined;
    },
    {
      path: "/admin/settings/payment";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/payment")>;
      $$route?: undefined;
    },
    {
      path: "/admin/users/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/users/index")>;
      $$route?: undefined;
    },
    {
      path: "/(public)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(public)")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/admin";
      id: "/admin";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/admin")>;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/sales/";
          id: "/sales/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/sales/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/users/";
          id: "/users/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/users/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/settings";
          id: "/settings";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings")>;
          $$route?: undefined;
          children: readonly [
            {
              path: "/";
              id: "/";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/index")>;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/payment";
              id: "/payment";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/payment")>;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/membership";
              id: "/membership";
              page: true;
              $component: FileRouteLazyRef<typeof import("./src/routes/admin/settings/membership")>;
              $$route?: undefined;
              children?: undefined;
            }
          ];
        }
      ];
    },
    {
      path: "/";
      id: "/(auth)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(auth)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/sign-in";
          id: "/sign-in";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/sign-in")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)/sign-in")>;
          children?: undefined;
        },
        {
          path: "/register";
          id: "/register";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/register")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(auth)/register")>;
          children?: undefined;
        },
        {
          path: "/activate/:key";
          id: "/activate/:key";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(auth)/activate/[key]")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/account";
      id: "/account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/account/index")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/";
      id: "/(public)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(public)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(public)/index")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/(public)/index")>;
          children?: undefined;
        },
        {
          path: "/memberships/";
          id: "/memberships/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(public)/memberships/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/memberships/:id";
          id: "/memberships/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(public)/memberships/[id]")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    }
  ];
}
