// Generated by @solidjs/vite-plugin (start.env) — do not edit.
// Regenerated on every dev server and build start from env.ts.
// Keep this file (and the schema) inside your tsconfig "include".

declare module 'virtual:env/client' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "VITE_APP_NAME": __Out<__Schema["client"]["VITE_APP_NAME"]>;
  };
  export { env };
  export default env;
}

declare module 'virtual:env/server' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "SESSION_SECRET": __Out<__Schema["server"]["SESSION_SECRET"]>;
    readonly "NAME": __Out<__Schema["server"]["NAME"]>;
    readonly "TIMEZONE": __Out<__Schema["server"]["TIMEZONE"]>;
    readonly "LOCALE": __Out<__Schema["server"]["LOCALE"]>;
    readonly "CURRENCY": __Out<__Schema["server"]["CURRENCY"]>;
    readonly "SALE_TAX_RATE": __Out<__Schema["server"]["SALE_TAX_RATE"]>;
    readonly "CONVENIENCE_FEE": __Out<__Schema["server"]["CONVENIENCE_FEE"]>;
    readonly "MAIL_FROM": __Out<__Schema["server"]["MAIL_FROM"]>;
    readonly "MAIL_HOST": __Out<__Schema["server"]["MAIL_HOST"]>;
    readonly "MAIL_PORT": __Out<__Schema["server"]["MAIL_PORT"]>;
    readonly "MAIL_USER": __Out<__Schema["server"]["MAIL_USER"]>;
    readonly "MAIL_PASSWORD": __Out<__Schema["server"]["MAIL_PASSWORD"]>;
    readonly "STRIPE_PUBLISHABLE_KEY": __Out<__Schema["server"]["STRIPE_PUBLISHABLE_KEY"]>;
    readonly "STRIPE_SECRET_KEY": __Out<__Schema["server"]["STRIPE_SECRET_KEY"]>;
    readonly "STRIPE_TAX_RATE_ID": __Out<__Schema["server"]["STRIPE_TAX_RATE_ID"]>;
    readonly "VITE_APP_NAME": __Out<__Schema["client"]["VITE_APP_NAME"]>;
  };
  export { env };
  export default env;
}
