CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    roles TEXT NOT NULL,
    creatorId INTEGER UNSIGNED NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT,
    activatedAt BIGINT
);

CREATE TABLE IF NOT EXISTS tokens (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userId INTEGER UNSIGNED NOT NULL,
    data TEXT NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT,
    expiresAt BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS membershipTypes (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    cover TEXT,
    duration INTEGER NOT NULL,
    price INTEGER NOT NULL,
    maxFreeSecondaries INTEGER NOT NULL,
    paidSecondaryPrice INTEGER NOT NULL,
    maxPaidSecondaries INTEGER NOT NULL,
    isActive INTEGER NOT NULL,
    isPublic INTEGER NOT NULL,
    creatorId INTEGER NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT
);

CREATE TABLE IF NOT EXISTS paymentMethods (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT NOT NULL,
    isActive INTEGER NOT NULL,
    isPublic INTEGER NOT NULL,
    creatorId INTEGER NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT
);

CREATE TABLE IF NOT EXISTS sales (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    status TEXT NOT NULL,
    source TEXT NOT NULL,
    isTaxable INTEGER NOT NULL,
    checkoutId TEXT,
    creatorId INTEGER NOT NULL,
    customerId INTEGER NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT
);

CREATE TABLE IF NOT EXISTS saleItems (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    saleId INTEGER NOT NULL,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    price INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    creatorId INTEGER NOT NULL,
    customerId INTEGER NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT,
    deletedAt BIGINT
);