CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    roles TEXT NOT NULL,
    creatorId BIGINT UNSIGNED NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT,
    activatedAt BIGINT
);

CREATE TABLE IF NOT EXISTS tokens (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userId BIGINT UNSIGNED NOT NULL,
    data TEXT NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    createdAt BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP()),
    updatedAt BIGINT,
    expiresAt BIGINT NOT NULL
);
