CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    roles TEXT NOT NULL,
    "creatorId" INTEGER NOT NULL,
    "createdAt" BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
    "updatedAt" BIGINT,
    "activatedAt" BIGINT
);

CREATE TABLE IF NOT EXISTS tokens (
    id SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    data TEXT NOT NULL,
    purpose TEXT NOT NULL,
    "createdAt" BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
    "updatedAt" BIGINT,
    "expiresAt" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "membershipTypes" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    cover TEXT,
    duration INTEGER NOT NULL,
    price INTEGER NOT NULL,
    "maxFreeSecondaries" INTEGER NOT NULL,
    "paidSecondaryPrice" INTEGER NOT NULL,
    "maxPaidSecondaries" INTEGER NOT NULL,
    "isActive" INTEGER NOT NULL,
    "isPublic" INTEGER NOT NULL,
    "creatorId" INTEGER NOT NULL,
    "createdAt" BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
    "updatedAt" BIGINT
);
