@extends('layout.admin')

@section('title', 'Sales')

@section ('subtitle', 'Manage Sale')

@section ('icon', 'dollar')

@section('content')

  <div class="ui floating secondary dropdown button">
    <i class="plus icon"></i> New Sale<i class="dropdown icon"></i>
    <div class="menu">
      @foreach ($eventTypes as $eventType)
        <a href={{ route('admin.sales.create', $eventType) }} class="item">{{ $eventType->name }}</a>
      @endforeach
    </div>
  </div>

  <br /><br />
  
  {{-- The rest of this content is all generated by React. Check assets/js/admin/sales --}}

  <div id="sales-index"></div>

@endsection
