FROM archlinux:latest

RUN pacman -Syy

RUN pacman -S php composer sqlite3 php-sqlite php-gd --noconfirm

RUN echo 'extension=gd' >> /etc/php/php.ini
RUN echo 'extension=pdo_sqlite' >> /etc/php/php.ini
RUN echo 'extension=sqlite3' >> /etc/php/php.ini
RUN echo 'zend_extension=opcache' >> /etc/php/php.ini
RUN echo 'extension=iconv' >> /etc/php/conf.d/extensions.ini
RUN echo 'extension=intl' >> /etc/php/conf.d/extensions.ini

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

COPY . .

RUN sqlite3 database/database.sqlite .databases .quit

#RUN composer install

#RUN php artisan migrate:fresh --seed

RUN php artisan storage:link

RUN php artisan config:cache

RUN php artisan key:generate

EXPOSE 8000

CMD php artisan serve --host 0.0.0.0 --env development
