networks:
    astral:
        external: true
services:
    server:
        image: localhost/astral:beta
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www/html
        networks:
            - astral
        environment:
            - DB_DATABASE=/var/www/html/database/database.sqlite
