/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authActivateRouteImport } from './routes/(auth)/activate'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as publicMembershipsIndexRouteImport } from './routes/(public)/memberships/index'
import { Route as AdminSettingsPaymentRouteImport } from './routes/admin/settings/payment'
import { Route as AdminSettingsMembershipRouteImport } from './routes/admin/settings/membership'
import { Route as publicMembershipsTypeIdRouteImport } from './routes/(public)/memberships/$typeId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authActivateRoute = authActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const publicMembershipsIndexRoute = publicMembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AdminSettingsPaymentRoute = AdminSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsMembershipRoute = AdminSettingsMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const publicMembershipsTypeIdRoute = publicMembershipsTypeIdRouteImport.update({
  id: '/memberships/$typeId',
  path: '/memberships/$typeId',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/activate': typeof authActivateRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/memberships/$typeId': typeof publicMembershipsTypeIdRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/memberships/': typeof publicMembershipsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/activate': typeof authActivateRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/': typeof publicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/memberships/$typeId': typeof publicMembershipsTypeIdRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/memberships': typeof publicMembershipsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/(auth)/activate': typeof authActivateRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(public)/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(public)/memberships/$typeId': typeof publicMembershipsTypeIdRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/(public)/memberships/': typeof publicMembershipsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/settings'
    | '/activate'
    | '/register'
    | '/sign-in'
    | '/'
    | '/admin/'
    | '/memberships/$typeId'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/memberships/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/register'
    | '/sign-in'
    | '/'
    | '/admin'
    | '/memberships/$typeId'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/memberships'
    | '/admin/settings'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/admin'
    | '/admin/settings'
    | '/(auth)/activate'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/(public)/'
    | '/admin/'
    | '/(public)/memberships/$typeId'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/(public)/memberships/'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/activate': {
      id: '/(auth)/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof authActivateRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/(public)/memberships/': {
      id: '/(public)/memberships/'
      path: '/memberships'
      fullPath: '/memberships/'
      preLoaderRoute: typeof publicMembershipsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/admin/settings/payment': {
      id: '/admin/settings/payment'
      path: '/payment'
      fullPath: '/admin/settings/payment'
      preLoaderRoute: typeof AdminSettingsPaymentRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/membership': {
      id: '/admin/settings/membership'
      path: '/membership'
      fullPath: '/admin/settings/membership'
      preLoaderRoute: typeof AdminSettingsMembershipRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/(public)/memberships/$typeId': {
      id: '/(public)/memberships/$typeId'
      path: '/memberships/$typeId'
      fullPath: '/memberships/$typeId'
      preLoaderRoute: typeof publicMembershipsTypeIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authActivateRoute: typeof authActivateRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authActivateRoute: authActivateRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicMembershipsTypeIdRoute: typeof publicMembershipsTypeIdRoute
  publicMembershipsIndexRoute: typeof publicMembershipsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicMembershipsTypeIdRoute: publicMembershipsTypeIdRoute,
  publicMembershipsIndexRoute: publicMembershipsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsMembershipRoute: typeof AdminSettingsMembershipRoute
  AdminSettingsPaymentRoute: typeof AdminSettingsPaymentRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsMembershipRoute: AdminSettingsMembershipRoute,
  AdminSettingsPaymentRoute: AdminSettingsPaymentRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
