/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsPaymentRouteImport } from './routes/admin/settings/payment'
import { Route as AdminSettingsMembershipRouteImport } from './routes/admin/settings/membership'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsPaymentRoute = AdminSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsMembershipRoute = AdminSettingsMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/membership': typeof AdminSettingsMembershipRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/register'
    | '/sign-in'
    | '/admin/settings'
    | '/admin/'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/admin'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/register'
    | '/sign-in'
    | '/admin/settings'
    | '/admin/'
    | '/admin/settings/membership'
    | '/admin/settings/payment'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/payment': {
      id: '/admin/settings/payment'
      path: '/payment'
      fullPath: '/admin/settings/payment'
      preLoaderRoute: typeof AdminSettingsPaymentRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/membership': {
      id: '/admin/settings/membership'
      path: '/membership'
      fullPath: '/admin/settings/membership'
      preLoaderRoute: typeof AdminSettingsMembershipRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
  }
}

interface AdminSettingsRouteRouteChildren {
  AdminSettingsMembershipRoute: typeof AdminSettingsMembershipRoute
  AdminSettingsPaymentRoute: typeof AdminSettingsPaymentRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsMembershipRoute: AdminSettingsMembershipRoute,
  AdminSettingsPaymentRoute: AdminSettingsPaymentRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
