<?php

namespace App\Tests;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

abstract class BaseWebTestCase extends WebTestCase
{
    public static User $user;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        /**
         * @var UserPasswordHasherInterface $passwordHasher
         */
        $passwordHasher = static::getContainer()->get(UserPasswordHasherInterface::class);

        $faker = \Faker\Factory::create();

        self::$user = new User(
            email: $faker->email(),
            firstName: $faker->firstName(),
            lastName: $faker->lastName(),
            password: password_hash($faker->password(), PASSWORD_DEFAULT)
        );

        // $entityManager->persist(self::$user);

        // $entityManager->flush();

        self::$user->setPassword($passwordHasher->hashPassword(self::$user, $faker->password()));

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:database:drop --force --quiet',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:database:create --quiet',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:schema:create --quiet',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );
    }
}
