<?php

namespace App\Tests;

use App\Entity\EventType;
use App\Entity\TicketType;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

abstract class BaseWebTestCase extends WebTestCase
{
    public static User $user;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        $faker = \Faker\Factory::create();

        self::$user = new User(
            email: $faker->email(),
            firstName: $faker->firstName(),
            lastName: $faker->lastName(),
            dateOfBirth: new \DateTimeImmutable(),
        );

        self::$user->setPassword($faker->password());

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:database:drop --force',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:database:create',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );

        passthru(
            sprintf(
                'APP_ENV=%s php "%s/../bin/console" doctrine:schema:create',
                $_ENV['APP_ENV'],
                __DIR__
            )
        );
    }
}
